create table activo (id bigint not null auto_increment, descripcion varchar(255), fecha date, primary key (id))
create table acumulado_caja (id bigint not null auto_increment, egreso float, fecha datetime, ingreso float, saldo float, version bigint not null, caja_id bigint, instrumento_id bigint, moneda_id bigint, primary key (id))
create table acumulado_cli (id bigint not null auto_increment, acum_ano float, acum_mes float, ano integer, fecha_ult_op datetime, mes integer, version bigint not null, fk_cli_id bigint, moneda_id bigint, primary key (id))
create table amenaza (id bigint not null auto_increment, codigo varchar(255), tipo varchar(255), fk_origen_amenaza bigint, primary key (id))
create table archivos_generados (id bigint not null auto_increment, estado varchar(255), fecha_creacion datetime, fecha_desde date, fecha_hasta date, file_name varchar(255), observaciones varchar(255), semana date, primary key (id))
create table cancelado (id bigint not null auto_increment, descripcion varchar(255), fecha date, primary key (id))
create table cliente (id bigint not null auto_increment, localidad varchar(255), apellido varchar(255), codigo_postal varchar(255), direccion varchar(255), documento varchar(255), email varchar(255), firma_pep date, fecha_nac date, nombre varchar(255), observaciones varchar(255), pep bit, telefono varchar(255), venc_doc date, param_estado_civ bigint, param_pais_origen bigint, param_pais_res bigint, fk_param_provincia bigint, fk_param_tipodoc bigint, primary key (id))
create table cotizacion (id bigint not null auto_increment, cotizacion_canje float, comision_cmp float, comision_vta float, cotizacion_cmp float, cotizacion_vta float, fecha datetime, fk_entidad bigint, fk_instrumento bigint, fk_moneda bigint, fk_moneda_base bigint, fk_tipo_cambio bigint, primary key (id))
create table impacto (id bigint not null auto_increment, calificacion varchar(255), valor integer, valor_monetario varchar(255), primary key (id))
create table incidente (id bigint not null auto_increment, activa bit, descripcion varchar(255), fecha_hora datetime, fecha_cierre datetime, responsable_resolucion varchar(255), solucion varchar(255), fk_clasificacion_id bigint, fk_tipo_inc bigint, fk_user_id bigint, primary key (id))
create table item (id bigint not null auto_increment, name varchar(255), price float, quantity integer, primary key (id))
create table my_revision (id integer not null auto_increment, timestamp bigint not null, user_name varchar(255), primary key (id))
create table operacion (id bigint not null auto_increment, fecha_hora datetime, monto_mnd_base_op float, observacion varchar(255), tipo_mov varchar(255), valor_cotizacion_aplicado float, fk_caja_id bigint, fk_cli_id bigint, estado bigint, fk_tipo_cam bigint, fk_tipo_op bigint, fk_user_id bigint, primary key (id))
create table operacion_item (id bigint not null auto_increment, fuente varchar(255), monto float, monto_rec_vlt float, orden integer, fk_caja_id bigint, fk_cotizacion_id bigint, fk_instrumnto bigint not null, fk_moneda bigint not null, fk_movimiento bigint, fk_operacion_id bigint not null, primary key (id))
create table origen_amenaza (id bigint not null auto_increment, origen varchar(255), primary key (id))
create table parametros (id bigint not null auto_increment, codigo varchar(255), sub_valor varchar(255), tipo varchar(255), valor varchar(255), primary key (id))
create table probalidad_ocurrencia (id bigint not null auto_increment, calificacion varchar(255), valor integer, primary key (id))
create table proyecto (id bigint not null auto_increment, alcance varchar(255), costo_estimado double precision, fecha_fin date, fecha_inicio date, objetivo varchar(255), recursos_humanos varchar(255), recursos_tecnicos varchar(255), primary key (id))
create table proyecto_aud (id bigint not null, rev integer not null, revtype tinyint, alcance varchar(255), costo_estimado double precision, fecha_fin date, fecha_inicio date, objetivo varchar(255), recursos_humanos varchar(255), recursos_tecnicos varchar(255), primary key (id, rev))
create table proyecto_riesgo (proyecto_id bigint not null, riesog_id bigint not null)
create table proyecto_riesgo_aud (rev integer not null, proyecto_id bigint not null, riesog_id bigint not null, revtype tinyint, primary key (rev, proyecto_id, riesog_id))
create table riesgo (id bigint not null auto_increment, afecta_confiabilidad bit, afecta_disponibilidad bit, afecta_integridad bit, codigo_formulario varchar(255), codigo_riesgo varchar(255), descripcion varchar(255), fecha_analisis date, fecha_aprobacion date, responsable varchar(255), fk_amenaza bigint, fk_impacto bigint, fk_prob_ocur bigint, fk_riesgo_inherente_valor bigint, fk_riesgo_residual_valor bigint, fk_salvaguarda bigint, fk_usuario_auditor bigint, fk_usuario_creador bigint, primary key (id))
create table riesgo_aud (id bigint not null, rev integer not null, revtype tinyint, afecta_confiabilidad bit, afecta_disponibilidad bit, afecta_integridad bit, codigo_formulario varchar(255), codigo_riesgo varchar(255), descripcion varchar(255), fecha_analisis date, fecha_aprobacion date, responsable varchar(255), fk_amenaza bigint, fk_impacto bigint, fk_prob_ocur bigint, fk_riesgo_inherente_valor bigint, fk_riesgo_residual_valor bigint, fk_salvaguarda bigint, fk_usuario_auditor bigint, fk_usuario_creador bigint, primary key (id, rev))
create table riesgo_inherente (id bigint not null auto_increment, calificacion varchar(255), valor integer, primary key (id))
create table riesgo_inherente_valor (id bigint not null auto_increment, valor integer, fk_riesgo_inherente bigint, primary key (id))
create table riesgo_inherente_valor_aud (id bigint not null, rev integer not null, revtype tinyint, valor integer, fk_riesgo_inherente bigint, primary key (id, rev))
create table riesgo_residual (id bigint not null auto_increment, calificacion varchar(255), valor integer, primary key (id))
create table riesgo_residual_valor (id bigint not null auto_increment, valor integer, fk_riesgo_residual bigint, primary key (id))
create table riesgo_residual_valor_aud (id bigint not null, rev integer not null, revtype tinyint, valor integer, fk_riesgo_residual bigint, primary key (id, rev))
create table salvaguarda (id bigint not null auto_increment, descripcion varchar(255), fk_impacto bigint, fk_prob_ocur bigint, fk_tipo_salvaguarda bigint, primary key (id))
create table salvaguarda_aud (id bigint not null, rev integer not null, revtype tinyint, descripcion varchar(255), fk_impacto bigint, fk_prob_ocur bigint, fk_tipo_salvaguarda bigint, primary key (id, rev))
create table salvaguarda_tipo (id bigint not null auto_increment, descripcion varchar(255), valor integer, primary key (id))
create table sesion_caja (id bigint not null auto_increment, fin_sesion datetime, inicio_sesion datetime, fk_caja bigint, fk_user bigint, primary key (id))
create table solucionado (id bigint not null auto_increment, descripcion varchar(255), fecha date, primary key (id))
create table tope_operacion (id bigint not null auto_increment, fecha_alta datetime, tope_ano float, tope_mes float, primary key (id))
create table usuario (id bigint not null auto_increment, email varchar(255), password varchar(255), role integer, primary key (id))
alter table cliente add constraint UK_g18g15ijpoftfxm5v87awpbym unique (documento)
alter table acumulado_caja add constraint FKbly3c8c0y5w837xdm6lcu0vif foreign key (caja_id) references parametros (id)
alter table acumulado_caja add constraint FKr2byoefenlxoe2ngmoq0vhev6 foreign key (instrumento_id) references parametros (id)
alter table acumulado_caja add constraint FKl5mum3tdbops4m1hwirkfwi8d foreign key (moneda_id) references parametros (id)
alter table acumulado_cli add constraint FKjgydas5oes85w9xrb8yw21987 foreign key (fk_cli_id) references cliente (id)
alter table acumulado_cli add constraint FK4gp3qtc3jk3n2yu3j6awjh4sh foreign key (moneda_id) references parametros (id)
alter table amenaza add constraint FKgh6rxqouf1hwdn6yrmw5746h4 foreign key (fk_origen_amenaza) references origen_amenaza (id)
alter table cliente add constraint FKiqncbll4nvdb3xurjat2945pd foreign key (param_estado_civ) references parametros (id)
alter table cliente add constraint FK3n82dg3xinrqtwpipq4ytete7 foreign key (param_pais_origen) references parametros (id)
alter table cliente add constraint FKpeibhhh3o5l4d9f6pj4rg186t foreign key (param_pais_res) references parametros (id)
alter table cliente add constraint FK1yot4fs79c7iror1dl1ajgwti foreign key (fk_param_provincia) references parametros (id)
alter table cliente add constraint FKismyaqugkhixrt05m7r2xklpk foreign key (fk_param_tipodoc) references parametros (id)
alter table cotizacion add constraint FKi1130ciglxwf9wrgd06e7fkpt foreign key (fk_entidad) references parametros (id)
alter table cotizacion add constraint FKhvh312j55prv0ij4ilrgom99l foreign key (fk_instrumento) references parametros (id)
alter table cotizacion add constraint FKr9dn93xnm8tp1su6qo4i8usa8 foreign key (fk_moneda) references parametros (id)
alter table cotizacion add constraint FKdclnvxhad59jl3f61433gphlx foreign key (fk_moneda_base) references parametros (id)
alter table cotizacion add constraint FKafteh5xxt0xt7y852v29mxthp foreign key (fk_tipo_cambio) references parametros (id)
alter table incidente add constraint FK639owqgnbuifqut2hvml7fwe1 foreign key (fk_clasificacion_id) references parametros (id)
alter table incidente add constraint FKqt7cg6khs34c031bbpe0jp8ts foreign key (fk_tipo_inc) references parametros (id)
alter table incidente add constraint FKm9260iy7b1hgykbr55v9kad1f foreign key (fk_user_id) references usuario (id)
alter table operacion add constraint FK8yej4ityagqwdmewyj0njh6k6 foreign key (fk_caja_id) references parametros (id)
alter table operacion add constraint FK5vd3mumy37wtq95vgd1om51qg foreign key (fk_cli_id) references cliente (id)
alter table operacion add constraint FK24q2cs0gn579ik0esgn24jggr foreign key (estado) references parametros (id)
alter table operacion add constraint FKhx1730mce1tsal9t4xso9l8yf foreign key (fk_tipo_cam) references parametros (id)
alter table operacion add constraint FKmn2lfjwbd1kf8irqfoorj2obn foreign key (fk_tipo_op) references parametros (id)
alter table operacion add constraint FK969ux8hb6wiqvdubi9l493lh9 foreign key (fk_user_id) references usuario (id)
alter table operacion_item add constraint FKmordxgfmyx26toymgg4jeaaca foreign key (fk_caja_id) references parametros (id)
alter table operacion_item add constraint FKfw2p1dnh8v0vhjvtmgux67v7x foreign key (fk_cotizacion_id) references cotizacion (id)
alter table operacion_item add constraint FKewh0o1kyi2qubblgs1dwxmwt1 foreign key (fk_instrumnto) references parametros (id)
alter table operacion_item add constraint FKim1upcae2w7qvj6x62t7v40bb foreign key (fk_moneda) references parametros (id)
alter table operacion_item add constraint FK6dltf5lludmqtr2eymu73awic foreign key (fk_movimiento) references parametros (id)
alter table operacion_item add constraint FK9hxj0t21h6i04ai3spcxwx484 foreign key (fk_operacion_id) references operacion (id)
alter table proyecto_aud add constraint FKsnenn0lk93ci0tpeiooedfass foreign key (rev) references my_revision (id)
alter table proyecto_riesgo add constraint FKhvsfop55ff3vt3tiy2vk5p5bl foreign key (riesog_id) references riesgo (id)
alter table proyecto_riesgo add constraint FKawjre2u3rqh8mpjdm6g1ue2mf foreign key (proyecto_id) references proyecto (id)
alter table proyecto_riesgo_aud add constraint FKiloytug4pevdqy69vlfvtqvxg foreign key (rev) references my_revision (id)
alter table riesgo add constraint FK8cqv30vtfbblta973x49sop4l foreign key (fk_amenaza) references amenaza (id)
alter table riesgo add constraint FK7gcovvh4i89ddvc51hxtv7inf foreign key (fk_impacto) references impacto (id)
alter table riesgo add constraint FK569wkdgnr57iohf6y78o3u47k foreign key (fk_prob_ocur) references probalidad_ocurrencia (id)
alter table riesgo add constraint FKs4vdqhxexm42hfx27xc11c2mi foreign key (fk_riesgo_inherente_valor) references riesgo_inherente_valor (id)
alter table riesgo add constraint FKdqvkbtvexlwwcc8ptxnneark8 foreign key (fk_riesgo_residual_valor) references riesgo_residual_valor (id)
alter table riesgo add constraint FKedwm9usnkd19h5alpbnikr9wp foreign key (fk_salvaguarda) references salvaguarda (id)
alter table riesgo add constraint FKhyo9c4puqkg1naw1d0kmn8ia4 foreign key (fk_usuario_auditor) references usuario (id)
alter table riesgo add constraint FKlkcjyxmth96rgt8h4dwc9c2ji foreign key (fk_usuario_creador) references usuario (id)
alter table riesgo_aud add constraint FKppgp5985hoe2eub2ml2kaochn foreign key (rev) references my_revision (id)
alter table riesgo_inherente_valor add constraint FKtgaabahmdjpuw63sinp3mkqg6 foreign key (fk_riesgo_inherente) references riesgo_inherente (id)
alter table riesgo_inherente_valor_aud add constraint FKmipruxqi0wyjf6ogfve73e5mi foreign key (rev) references my_revision (id)
alter table riesgo_residual_valor add constraint FKqsynbj7vyqexohp0kr74c8nuk foreign key (fk_riesgo_residual) references riesgo_residual (id)
alter table riesgo_residual_valor_aud add constraint FKdcltmi46eleg94e0scj99rh6a foreign key (rev) references my_revision (id)
alter table salvaguarda add constraint FKoxrhcy1vvwpq63vhalqqwo2bi foreign key (fk_impacto) references impacto (id)
alter table salvaguarda add constraint FKmhpjv47e5i8gas247m8bupcml foreign key (fk_prob_ocur) references probalidad_ocurrencia (id)
alter table salvaguarda add constraint FKavlu14nfk9s280wg8jfbafdvk foreign key (fk_tipo_salvaguarda) references salvaguarda_tipo (id)
alter table salvaguarda_aud add constraint FKlwgdsbnsnx7qqr40yqsnadonu foreign key (rev) references my_revision (id)
alter table sesion_caja add constraint FK8oi6emyic3bgs8h45pcos7ep9 foreign key (fk_caja) references parametros (id)
alter table sesion_caja add constraint FKeyksewx40727jmnuiw5da7m95 foreign key (fk_user) references usuario (id)
